{
    'name': 'CRM Base',
    'version': '11.0.0.0',
    'category': 'Sales',
    'author': "Allion Technologies PVT Ltd",
    'website': 'www.alliontechnologies.com',
    'summary': 'This plugin customized the CRM module ',
    'description': "This plugin customized the CRM module according to new requirements",
    'depends': [
        'mail',
        'crm',
        'product',
        'sale',
        'account',
        'base'
    ],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'views/crm_departments_view.xml',
        'views/res_partner_view.xml',
        'views/sale_view.xml',
        'views/crm_lead_views.xml',
        'report/sale_report.xml',
        'report/report_template_inherit.xml',
        'report/report_saleorder.xml',
        'report/invoice_inherit.xml',
        'views/crm_departments_menu.xml',
        'views/crm_lead_menus.xml',
        'data/mail_template_data_new.xml',
        'data/crm_stage_data.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
