{
    'name': 'Account Expenses',
    'version': '1.0',
    'sequence': 0,
    'author': "Allion Technologies PVT Ltd",
    'website': 'http://www.alliontechnologies.com/',
    'summary': 'Account Expenses',
    'description': """This module manages Account Expenses""",
    'depends': [
        'account',
        'account_invoicing',
    ],
    'data': [
        'data/ir_sequence_data.xml',
        'reports/cheque_print_paperformat.xml',
        'reports/payment_voucher_paperformat.xml',
        'reports/payment_voucher_report.xml',
        'reports/action_payment_voucher_report.xml',
        'reports/cheque_ac_payee_only_with_20.xml',
        'reports/cheque_ac_payee_only_without_20.xml',
        'reports/cheque_cash_with_20.xml',
        'reports/cheque_cash_without_20.xml',
        'reports/inherited_payment_receipt.xml',
        'views/account_expense_view.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}