{
    'name': 'Odoo Biometric Integration',
    'version': '1.0',
    'category': 'Human Resources',
    'sequence': 1,
    'author': "Allion Technologies PVT Ltd",
    'website': 'http://www.alliontechnologies.com/',
    'summary': 'Middleware for Biometric device and Odoo',
    'description': """Sync all the HR data with the biometric device and get attendance detail from the device through Odoo HR Attendance module""",
    'depends': [
        'hr',
        'resource',
        'os_hr_lk',
        'hr_attendance',
        'hr_payroll',
        'hr_processes_configuration',
    ],
    'external_dependencies': {
        'python': ['zklib'],
    },
    'data': [
        'views/biometic_device_config_view.xml',
        'views/biometric_attnd_log_view.xml',
        'views/hr_attendance_view.xml',
        'views/resource_view.xml',
        'views/resource_calendar_inherit_view.xml',
        'views/hr_employee_inherit.xml',
        'wizard/biometric_device_view.xml',
        'wizard/attendance_calc_wizard_view.xml',
        'wizard/attendance_report_wizard_view.xml',
        'wizard/nopay_report_wizard_view.xml',
        'wizard/attendance_report_wizard_view_other.xml',
        'wizard/overtime_calc_wizard.xml',
        'security/ir.model.access.csv',
        'data/late_attendance_server_action.xml',
        'data/over_time_server_action.xml',
        'data/monthly_overtime_server_action.xml',
        'data/default_data_hr_holiday_status.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}

